#!/usr/bin/env python3
import sys
from pathlib import Path

# Автоматически находим корень проекта games_project_vituk
project_root = Path(__file__).resolve().parents[3] / "games_project_vituk"
sys.path.insert(0, str(project_root))

from games_project_vituk.VD_games.scripts.VD_even import main
main()
